### ISSUE TITLE
Problems with npm run palico bootstrap

### ISSUE THREAD

**Issue by tyler-lemke** [palico-ai/palico-ai#159]
When I run this command I get the following error:

No containers to stop
Creating Containers...
node:internal/fs/promises:859
  return await PromisePrototypeThen(
         ^

Error: ENOTDIR: not a directory, mkdir 'C:\git\palico-example\package.json'
    at async mkdir (node:internal/fs/promises:859:10) {
  errno: -4052,
  code: 'ENOTDIR',
  syscall: 'mkdir',
  path: 'C:\\git\\palico-example\\package.json'
}

Node.js v21.7.3

Digging into the code I think this is the culprit. I am assuming that the code works for Mac/Linux and not windows installations?

  static async getWorkspaceRootDir(): Promise<string> {
    if (this.projectPath) {
      return this.projectPath;
    }
    const fullPath = await findup('package.json');
    const path = fullPath?.replace(/\/package.json$/, '');
    if (!path) {
      throw new Error('Failed to find project root');
    }
    this.projectPath = path;
    return path;
  }

My suggested fix is to use the built in node path commands to avoid this issue or add unit tests to this code. 

  static async getWorkspaceRootDir(): Promise<string> {
  if (this.projectPath) {
    return this.projectPath;
  }
  const fullPath = await findup('package.json');
  if (!fullPath) {
    throw new Error('Failed to find project root');
  }
  const projectRoot = path.dirname(fullPath);
  this.projectPath = projectRoot;
  return projectRoot;
}

Thanks for this great project! Can't wait to use it once I get this part working.

**Comment by shikdernyc** [comment]
Hi Tyler, thanks for checking out the project and creating this issue! You're right, I should be using the node path library to handle path manipulation.

I do not immediately have access to a windows machine at the moment -- looking into some cross platform testing options to ensure we have better support across all platforms. Will try to get this resolved by EOW.

**Comment by shikdernyc** [comment]
The latest update should resolve this issue. You can update to the latest version by running
```
npm update @palico-ai/app
```
From there, you can follow the regular getting started guide: https://docs.palico.ai/getting_started/installation#add-your-openai-api-key
