### ISSUE TITLE
docker-compose vs docker compose

### ISSUE THREAD

**Issue by GyadavCC** [palico-ai/palico-ai#171]
[in the file generated at 
node_modules/@palico-ai/app/src/utils/build.js

](https://github.com/palico-ai/palico-ai/blob/47d627057564e4778f7e3ffb84b669c0c24e4f0c/packages/palico-app/src/utils/build.ts#L94)

we should have something like this 
```
  static async buildDockerImages() {
    const { composeFilePath } = await ProjectBuild.getDockerComposePath();
    const options = {
      cwd: path.dirname(composeFilePath),
      log: true,
      commandOptions: ['--no-cache']
    };

    try {
      await compose.buildAll(options);
      console.log('Docker images built successfully');
    } catch (error) {
      console.error('Error building Docker images:', error);
      throw error;
    }
  }
  
  ```
  when we try to ``` docker-compose -f ${composeFilePath} build --no-cache ``` 
  
  docker-compose is old.. is replaced by docker compose. The npm module compose that is already imported handles it. Lets use it. 
  
  here is the error i get 
  
  
  (base) palico-eval:~$ which docker

/usr/local/bin/docker
(base) palico-eval:~$ docker compose version
Docker Compose version v2.28.1-desktop.1
(base) palico-eval:~$ npm run palico bootstrap

> palico-eval@1.0.0 palico
> palico-app bootstrap

Stopping project's containers...
/bin/sh: docker-compose: command not found
No containers to stop
Creating Containers...
Building project's containers...
/bin/sh: docker-compose: command not found
node:internal/errors:984
  const err = new Error(message);
              ^

Error: Command failed: docker-compose -f /Users/gaurav/work/palico-eval/.palico/docker-compose.yml build --no-cache
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at ProjectBuild.<anonymous> (/Users/gaurav/work/palico-eval/node_modules/@palico-ai/app/src/utils/build.js:85:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gaurav/work/palico-eval/node_modules/tslib/tslib.js:166:62) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 24407,
  stdout: null,
  stderr: null
}

Node.js v20.12.2

**Comment by shikdernyc** [comment]
@GyadavCC thanks for creating the issue and digging into the code to suggest a resolution! There are few other bugs I'm currently on related to project-setup. Looking to have all these resolved and released by the end of the week.
