### ISSUE TITLE
Install Sharp for Palico Studio

### ISSUE THREAD

**Issue by shikdernyc** [palico-ai/palico-ai#195]
https://nextjs.org/docs/messages/sharp-missing-in-production

**Comment by priyanshuverma-dev** [comment]
@shikdernyc  May I work on this issue

**Comment by shikdernyc** [comment]
Hey @priyanshuverma-dev, would love your help on this, thanks!

Checkout the contribution docs to get started: https://github.com/palico-ai/palico-ai/blob/main/CONTRIBUTING.md

**Comment by shikdernyc** [comment]
Let me know if something isn't clear on the CONTRIBUTING docs. Just added it to the repo.

**Comment by priyanshuverma-dev** [comment]
@shikdernyc How to reproduce this error

**Comment by shikdernyc** [comment]
Seems like just a standard requirement for NextJS for standalone builds. You can see this error on your own palico app in the docker container log

```
![image](https://github.com/user-attachments/assets/b81db210-3ba6-4fc5-bcf4-4cd24cf28af0)
```

I expect if you install sharp, this error should go away. Have not done further digging but will do more testing prior to next npm release.
