### ISSUE TITLE
Bug uuidv4 no longer supported

### ISSUE THREAD

**Issue by priyanshuverma-dev** [palico-ai/palico-ai#224]
**Describe the bug**
Dependencies of `@palico-ai/app` are outdated specially `uuidv4`.

**To Reproduce**
1. run command `npx palico init <project-name>`

**Expected behavior**
It should execute command without giving error.

**Screenshots**
![image](https://github.com/user-attachments/assets/5b58c830-5287-446c-86d4-a39c367f1b1c)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This issue can be fixed if update `uuidv4` dependency.

**Comment by priyanshuverma-dev** [comment]
@shikdernyc May I work on this issue

**Comment by shikdernyc** [comment]
Hey @priyanshuverma-dev , thanks for bringing up this issue. Since this is an urgent issue, i'll handle the fix.
