### ISSUE TITLE
Bug: Dockerfile not found

### ISSUE THREAD

**Issue by priyanshuverma-dev** [palico-ai/palico-ai#228]
**Describe the bug**

**To Reproduce**
1. Setup project `npx palico init sample-app`
2. get inside it and initialize selfhost `npm run selfhost:init`
3. Run `npm run selfhost:up`

**Expected behavior**
It should build `api` service properly.

**Screenshots**
![image](https://github.com/user-attachments/assets/420d4193-1dfa-48d2-87c6-915ebfa69aae)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have fixed it also and wanted to pull request.
May I work on this issue and pull.

**Comment by shikdernyc** [comment]
Hmm, weird it seems to be working on mac. Would love to see your pull request.
