### ISSUE TITLE
Fix NextJS caching issue with NextJS Apps

### ISSUE THREAD

**Issue by shikdernyc** [palico-ai/palico-ai#92]
There are various caching whenever we create a server-sided mutation. For example, creating a new experiment, or having a new trace. These mutations do not update on the client-side until the developer refreshes the page. Fix this issue

**Comment by spiderakm** [comment]
can you assign this to me

**Comment by shikdernyc** [comment]
Hi @spiderakm, sorry for the late reply. I want to fundamentally change how we handle fetching on the studio application. Since it's a fairly involved change spanning across lots of files, I would rather tackle this change myself.
